BlogAPP/authentication/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('profile/', views.UserProfile.as_view(), name='current user profile'),
    path('profile/<int:pk>', views.UserProfile.as_view(), name='user profile'),

    path('signin/', views.SignIn.as_view(), name='sign in'),
    path('signout/', views.SignOut.as_view(), name='sign out'),
    path('signup/', views.SignUp.as_view(), name='sign up')
]

from .receivers import *

BlogAPP/blogs_system/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('create_blog/', views.CreateBlogView.as_view(), name='create blog'),
    path('<int:pk>/', views.BlogDetailsView.as_view(), name='blog details'),
    path('<int:pk>/delete/', views.DeleteBlog.as_view(), name='delete blog'),

    path('create_post/', views.CreatePost.as_view(), name='create post'),
    # path('<int:pk>/delete_post/', views.DeletePost.as_view(), name='delete post'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BlogAPP/urls.py
from django.contrib import admin
from django.urls import path, include

from BlogAPP.blogs_system.views import LandingPage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPage.as_view(), name='homepage'),
    path('', include('BlogAPP.blogs_system.urls')),
    path('auth/', include('BlogAPP.authentication.urls'))

]

BlogAPP/authentication/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.contrib.auth.models import User

UserModel = get_user_model()


class Profile(models.Model):
    profile_picture = models.ImageField(
        upload_to='users',
        blank=True
    )
    user = models.OneToOneField(UserModel, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user}'

BlogAPP/blogs_system/models.py
from django.contrib.auth import get_user_model
from django.db import models
from BlogAPP.authentication.models import Profile

UserModel = get_user_model()


class Blog(models.Model):
    slug = models.SlugField(editable=False)
    name = models.CharField(max_length=30)
    picture = models.ImageField(upload_to='BlogsImage', null=True, blank=False)
    description = models.TextField()
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)

    def __int__(self):
        return self.id

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=30)
    picture = models.ImageField(upload_to='PostsImage', null=True, blank=False)
    text = models.TextField()
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)

    def __int__(self):
        return self.id

    def __str__(self):
        return self.title


class Comment(models.Model):
    text = models.TextField()
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)

BlogAPP/authentication/forms.py
from django.contrib.auth import forms as auth_forms
from django import forms

from BlogAPP.authentication.models import Profile
from common import form_mixins


class SignUpForm(form_mixins.BoostrapMixin, auth_forms.UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__init_fields__()


class SignInForm(form_mixins.BoostrapMixin, auth_forms.AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__init_fields__()


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('profile_picture',)

BlogAPP/blogs_system/forms.py
from django.forms import ModelForm

from BlogAPP.blogs_system.models import Blog, Post
from common import form_mixins


class CreationForm(ModelForm):
    class Meta:
        model = Blog
        fields = '__all__'
        exclude = ('user',)


class CreateBlogForm(form_mixins.BoostrapMixin, CreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__init_fields__()


class CreatePostForm(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        exclude = ('user',)


class CreatePost(form_mixins.BoostrapMixin, CreatePostForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__init_fields__()

BlogAPP/authentication/views.py
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views import generic as views
from django.contrib.auth import views as auth_views, login
from BlogAPP.authentication.forms import *
from BlogAPP.blogs_system.models import *


class UserProfile(views.UpdateView):
    template_name = 'authentication/profile.html'
    form_class = UserProfileForm
    model = Profile

    def get_success_url(self):
        return reverse_lazy('homepage')

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk', None)
        user = self.request.user if pk is None else User.objects.get(pk=pk)
        return user.profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = self.get_object().user
        context['current_profile'] = self.get_object().user != self.request.user
        context['blog'] = self.get_object().blog_set.all()
        return context


class SignUp(views.CreateView):
    template_name = 'authentication/signup.html'
    form_class = SignUpForm
    success_url = reverse_lazy('homepage')

    def form_valid(self, form):
        valid = super().form_valid(form)
        user = form.save()
        login(self.request, user)
        return valid


class SignIn(auth_views.LoginView):
    template_name = 'authentication/signin.html'
    form_class = SignInForm


class SignOut(auth_views.LogoutView):
    next_page = reverse_lazy('homepage')

BlogAPP/blogs_system/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, DeleteView, ListView
from django.contrib.auth import mixins as auth_mixins
from BlogAPP.blogs_system.forms import CreateBlogForm, CreatePostForm
from BlogAPP.blogs_system.models import Blog, Post


class LandingPage(auth_mixins.LoginRequiredMixin, ListView):
    template_name = 'index.html'
    model = Blog


class BlogDetailsView(DetailView):
    template_name = 'blogs/details.html'
    model = Blog

    def get_context_data(self, **kwargs):
        blog = Blog.objects.get(pk=self.kwargs.get('pk'))

        context = super().get_context_data(**kwargs)
        context['post'] = self.get_object().post_set.all()
        context['can_delete'] = blog.user == self.request.user.profile
        return context


class CreateBlogView(auth_mixins.LoginRequiredMixin, CreateView):
    form_class = CreateBlogForm
    model = Blog
    template_name = 'blogs/create.html'
    success_url = reverse_lazy('homepage')

    def form_valid(self, form):
        valid = super().form_valid(form)
        todo = form.save()
        todo.user = self.request.user.profile
        todo.save()
        return valid


class PostListView(ListView):
    template_name = 'blogs/details.html'
    model = Post


class DeleteBlog(auth_mixins.LoginRequiredMixin, DeleteView):
    template_name = 'blogs/delete_blog.html'
    model = Blog

    def delete(self, request, *args, **kwargs):
        blog = Blog.objects.get(pk=self.kwargs.get('pk'))
        image = blog.picture

        if blog.user != request.user.profile:
            return HttpResponseRedirect('/')
        else:
            image.delete()
            self.get_object().delete()
            return redirect('homepage')


class CreatePost(auth_mixins.LoginRequiredMixin, CreateView):
    template_name = 'blogs/posts/create_post.html'
    form_class = CreatePostForm
    model = Post
    success_url = '/'

    def form_valid(self, form):
        valid = super().form_valid(form)
        post = form.save()
        post.user = self.request.user.profile
        post.save()
        return valid


class DeletePost(auth_mixins.LoginRequiredMixin, DeleteView):
    template_name = 'blogs/delete_blog.html'
    model = Post

    def get_success_url(self):
        return reverse_lazy('homepage')

templates/authentication/profile.html
{% extends 'base.html' %}

{% block site_content %}
    {% if current_profile %}
        <div class="text-center">
            <h1>{{ profile.username }}'s Profile !</h1>
            {% if profile.profile_picture %}
                <img class="" src="{{ profile.profile_picture.url }}" alt="Generic placeholder image"
                     width="140px"
                     height="140px">
            {% else %}
                <img class="rounded-circle mb-3" src="https://afribary.com/authors/anonymous-user/photo"
                     alt="Generic placeholder image" width="140"
                     height="140">
            {% endif %}
        <hr>
        {% if blog %}
            <h2 class='text-center'>These are {{ profile.username }}'s Blogs</h2>
            <div class="row">
                <div class="row">
                    {% for x in blog %}
                        <div class="col-lg-4">
                            <div class="card" style="width: 18rem;">
                                <div class="card-body">
                                    <h5 class="card-title">{{ x.name }} </h5>
                                    <a href="{% url 'blog details' x.pk %}">See Details </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% else %}
            <div class="text-center">
                <h2>You have no blogs</h2>
                <a href="{% url 'create blog' %}" class="btn btn-success">Add Blog</a>
            </div>
        {% endif %}
    {% else %}
        <div class="text-center">
            <h1>Hello, {{ profile.username }}!</h1>
            <h5>This is your profile</h5>
            {% if profile.profile_picture %}
                <img class="" src="{{ profile.profile_picture }}" alt="Generic placeholder image"
                     width="140px"
                     height="140px">
            {% else %}
                <img class="rounded-circle mb-3" src="https://afribary.com/authors/anonymous-user/photo"
                     alt="Generic placeholder image" width="140"
                     height="140">
            {% endif %}
            <div class="w-50 m-auto">
                <form action="{% url 'current user profile' %}" method="post" enctype="multipart/form-data">
                    {{ form }}
                    {% csrf_token %}
                    <button class="btn btn-primary">Upload</button>
                </form>
            </div>
        </div>
        <hr>
        {% if blog %}
            <h2 class='text-center'>These are you'r Blogs</h2>
            <div class="row">
                <div class="row">
                    {% for x in blog %}
                        <div class="col-lg-4">
                            <div class="card" style="width: 18rem;">
                                <div class="card-body">
                                    <h5 class="card-title">{{ x.name }} </h5>
                                    <a href="{% url 'blog details' x.pk %}">See Details </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% else %}
            <div class="text-center">
                <h2>You have no blogs</h2>
                <a href="{% url 'create blog' %}" class="btn btn-success">Add Blog</a>
            </div>
        {% endif %}
    {% endif %}
{% endblock %}

templates/authentication/signin.html
{% extends 'base.html' %}

{% block site_content %}
    <div class="child">
        <form action="{% url 'sign in' %}" method="post">
            {{ form }}
            {% csrf_token %}
            <button class="btn btn-success"> Sign In</button>
            or <a href="{% url 'sign up' %}">sign up</a>
        </form>
    </div>
{% endblock %}

templates/authentication/signup.html
{% extends 'base.html' %}

{% block site_content %}
    <div class="child">
        <form action="{% url 'sign up' %}" method="post">
            {{ form }}
            {% csrf_token %}
            <button class="btn btn-success"> Sign Up</button>
            or <a href="{% url 'sign in' %}">sign in</a>
        </form>
    </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
      crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="stylesheet" href="{% static 'css/navigation.css' %}">

<head>
    {% include 'partials/navigation.html' %}
    <meta charset="UTF-8">
    {% block site_title %}
        <title>Blogs</title>
    {% endblock %}
</head>
<body>
{% block site_content %}

{% endblock %}
</body>
</html>

templates/blogs/create.html
{% extends 'base.html' %}

{% block site_content %}
        <div class="child">
            <form method="POST" action="{% url 'create blog' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media }}
                {{ form }}
                <button class="btn btn-outline-warning">Create</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/blogs/delete_blog.html
{% extends 'base.html' %}
{% block site_content %}
        <div class="row">
            <div class="col-lg-12 text-center">
                <h1>Are you sure you want to delete {{ blog.name }}?</h1>
                <div class="m-auto d-flex justify-content-center">
                    <div class="m-2">
                        <form method="post" action="{% url 'delete blog' blog.id %}">{% csrf_token %}
                            {% csrf_token %}
                            <button class="btn btn-danger">
                                Confirm
                            </button>
                        </form>
                    </div>
                    <div class="m-2">
                        <a class="btn btn-primary" href="javascript:history.back()">No, go back</a>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/blogs/details.html
{% extends 'base.html' %}
{% block site_content %}
    {% if can_delete %}
        <a href="{% url 'delete blog' blog.id %}" class="btn btn-danger">Delete Blog</a>
    {% endif %}
    {% if post %}
        <a href="{% url 'create post' %}" class="btn btn-success">Create post</a>
        <h2 class='text-center'>All post's in {{ blog.name }}</h2>
        <div class="row">
            <div class="row">
                {% for x in post %}
                    <div class="col-lg-4">
                        <div class="card" style="width: 18rem;">
                            <div class="card-body">
                                <h5 class="card-title">{{ x.title }} </h5>
                                <p class="card-text">{{ x.text }}</p>
                                <p class="card-text"><strong> Owner: {{ x.user }}</strong></p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <div class="text-center">
            <h2>Don't have post's ! </h2>
            <a href="{% url 'create post' %}" class="btn btn-success">Create post</a>
        </div>
    {% endif %}
{% endblock %}

templates/blogs/posts/create_post.html
{% extends 'base.html' %}

{% block site_content %}
    <form method="post"> {% csrf_token %}
        {{ form }}
    <button class="btn btn-success">Create</button>
    </form>
{% endblock %}

templates/blogs/posts/delete_post.html
{% extends 'base.html' %}

{% block site_content %}
    Delete_post
{% endblock %}

templates/blogs/posts/search_post.html
{% if post %}
    <center> Search Result Found</center>
    {% for obj in post %}
        <h2><a>{{ blog.title }}</a></h2>
    {% endfor %}
{% else %}
        <center> Search Result Not Found Blog </center>
{% endif %}

templates/index.html
{% extends 'base.html' %}
{% block site_content %}
    <h1 class='text-center'>All Blogs</h1>
    <div class="container">
        <div class="row">
            {% for blog in blog_list %}
                <div class="col-sm-3">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-text"><a style="text-decoration: none; color: #ff0000"
                                                     href="{% url 'blog details' blog.id %}"> {{ blog }}</a>
                            </h5>
                            <h5 class="card-text" style="text-decoration: none">Owner: <a
                                    style="color: darkseagreen; text-decoration: none"
                                    href="{% url 'user profile' blog.user.user_id %}">{{ blog.user }}</a></h5>
                        </div>
                        {% if blog.picture %}
                            <img src="{{ blog.picture.url }}" alt="Image" class="card-img-top">
                        {% else %}
                            NOT PICTURE :)
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/partials/navigation.html
<header>
    <nav class="site-nav">
        <ul class="list-horizontal">
            {% if user.is_authenticated %}
                <li class="list-item">
                    <a class="navbar-brand" href="{% url 'homepage' %}">
                        Home
                    </a>
                </li>
                <li class="list-item">
                    <a class="navbar-brand" href="{% url 'create blog' %}">
                        Add Blog
                    </a>
                </li>
                <li class="list-item">
                    <a class="navbar-brand" href="{% url 'current user profile' %}">
                        Hello, {{ user.username }}
                    </a>
                </li>
                <li class="list-item">
                    <a class="navbar-brand" href="{% url 'sign out' %}">
                        Sign out
                    </a>
                </li>
            {% else %}
                <li class="list-item">
                    <a class="navbar-brand" href="{% url 'homepage' %}">
                        Home
                    </a>
                </li>
                <li class="list-item">
                    <a class="navbar-brand" href="{% url 'sign in' %}">
                        Sign in
                    </a>
                </li>
                <li class="list-item">
                    <a class="navbar-brand" href="{% url 'sign up' %}">
                        Sign up
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
</header>